version: "3.8"

services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: eoy-backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    environment:
      - DATABASE_URL=sqlite:///app/database.db
    depends_on:
      - db

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    container_name: eoy-frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: eoy-database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: eoy_directory
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
